### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by graisVictory** [chrisbanes/snapper#24] opened 2022-05-03 13:59 UTC
While performing a scroll a crash happened

    java.lang.NullPointerException
        at dev.chrisbanes.snapper.SnapperFlingBehavior.flingToIndex(SnapperFlingBehavior.kt:410)
        at dev.chrisbanes.snapper.SnapperFlingBehavior.access$flingToIndex(SnapperFlingBehavior.kt:288)
        at dev.chrisbanes.snapper.SnapperFlingBehavior$flingToIndex$1.invokeSuspend(Unknown Source:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by chrisbanes** [comment] 2022-05-03 14:17
Duplicate of #22

**Closed by chrisbanes** 2022-05-03 14:18 UTC
